# a simple ingress for our service: exposed ingress according to https://k3d.io/usage/guides/exposing_services/
# access via host:8081 - change hosts in hosts-file
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reference-project
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: reference-project
              port:
                number: 8080
  - host: jaeger.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: jaeger-all-in-one
              port:
                number: 16686
  - host: zipkin.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: zipkin-all-in-one
              port:
                number: 9411